name: Deploy Vite Portfolio

on:
  push:
    branches: ["master"]   # since your repo is on master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # ✅ updated

      - name: Setup Node
        uses: actions/setup-node@v4   # ✅ updated
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload build output
        uses: actions/upload-pages-artifact@v3   # ✅ latest version
        with:
          path: ./dist   # Vite outputs here

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4   # ✅ latest version
